### ISSUE TITLE
ReferenceError: Path is not defined

### ISSUE THREAD

**Issue by R-K-H** [DeviaVir/vue-bar#15]
Using expressVue so unable to pass this to Vue.use. That being said not entirely sure that this shouldn't work using the import alone. Wondering if there is something in the files that could be causing conflict or if there might be a way to install this using expressVue and serverside rendering.

From https://github.com/DeviaVir/vue-bar/blob/39fc7785bcdbd1c8881dd7f91a6c0109a9fdfbe9/src/components/bars.js#L63
```
 h(Path, {
```

Thanks.

**Comment by DeviaVir** [comment]
Are you able to supply a codepen or something similar showcasing the issue? Path here simply references the import of https://github.com/DeviaVir/vue-bar/blob/39fc7785bcdbd1c8881dd7f91a6c0109a9fdfbe9/src/components/path.js

**Comment by R-K-H** [comment]
Yea that was what was weird as it's just an import. 

My guess is with express-vue (https://www.npmjs.com/package/express-vue) (https://github.com/express-vue/express-vue) it's server side rendering, meaning I don't initialize Vue anywhere instead I use express-vue and then the middleware they provide. I've seen several reports from users

- https://github.com/express-vue/express-vue/issues/198
- https://github.com/express-vue/express-vue/issues/185
- https://github.com/express-vue/express-vue/issues/181
- https://github.com/express-vue/express-vue/issues/176

I just wasn't sure if you might know a way around this? If not I'll switch the app to Vue and then be able to handle what I need to be able to do. Just found it odd that I was able to get that far with this package only to have the import fail for it.

**Comment by DeviaVir** [comment]
I'm tempted to say this is not a problem with vue-bar specifically, as you've shown the issue is with multiple other resources as well, you may want to open an issue over at express-vue and link to this one.

**Comment by R-K-H** [comment]
Yea thanks, just wanted to see if you've ever come across anything like this before with it.

**Comment by DeviaVir** [comment]
@R-K-H sorry, no :(
