### ISSUE TITLE
Segregate Labels for backwards compatibility

### ISSUE THREAD

**Issue by zombiesplat** [DeviaVir/vue-bar#20]
When I made the update for the labels, I pretty much only did enough for my own needs. However that update was not backwards compatible and will break existing implementations.

My plan is to make the x-axis labels an optional parameter passed in as an array of text. This issue will serve to also let others know I am working on this if your build breaks in the meantime, update your packages.json for version 0.1.3

**Comment by smknstd** [comment]
hi @zombiesplat, not 100% sure about the initial need of segregating labels. Can you give more explanations ?

**Comment by zombiesplat** [comment]
My original PR (issue/7 Negative Bars) was because the original code did not accomodate for negative numbers. The math was very hard to understand because the axises were flipped upside down. 

This PR was to introduce an update to the labels to be passed in separately since they weren't always going to be 20 pixels high. However I believe the next release or the latest actually addresses this to be backwards compatible.

**Comment by smknstd** [comment]
I adapted the demo playground https://deviavir.github.io/vue-bar/

Is this working as expected ?

**Comment by zombiesplat** [comment]
Definitely
That's awesome!

**Comment by smknstd** [comment]
I think there is still an issue. Labels should probably be aligned when angle is > 45°

![Screenshot_2020-06-03 vuebars](https://user-images.githubusercontent.com/2412608/83674955-8ae4f080-a5d8-11ea-99dd-10c460f7ffe1.png)
