### ISSUE TITLE
Cannot set property 'boundary' of undefined

### ISSUE THREAD

**Issue by Xayer** [DeviaVir/vue-bar#3]
Hi!
I'm using the vue-bars module on a codepen project.
It appeared to work, however, I've encountered this error when trying to render a graph:
![](https://puu.sh/wr5Sj/d74003ab7c.png)
parameters:
```
<bars
       :data="numbers">
    </bars>
```
numbers is a data object with the following structure:
```
numbers: [
        { key: 1 },
        { key: 2 },
        { key: 3 },
      ]
```

[link to codepen project](https://codepen.io/xayer/project/editor/AqdenG/)

**Comment by DeviaVir** [comment]
@Xayer whoops, that's a bug indeed. To go around this, I'd advise to pass an array with numbers instead of an array with objects for now.

Like:

```
numbers: [0, 1, 2, 3]
```

**Comment by Xayer** [comment]
@DeviaVir Thanks for replying. Unfortunately it doesn't seem like turning it into an array helped for me, as I'm still encountering the same issue 🙁

**Comment by DeviaVir** [comment]
@Xayer is the live demo also not working for you? https://jsfiddle.net/nyh18bLq/91/

**Comment by Xayer** [comment]
@DeviaVir it's working just fine. So I guess it's on my project 😞
