### ISSUE TITLE
Rounding prop doesn't work

### ISSUE THREAD

**Issue by DavidGolodetsky** [DeviaVir/vue-bar#36]
Browser: Chrome

When I change the `rounding` prop it doesn't change anything.

My input:

```
   <bars
          data="[1, 2, 5, 9, 5, 10, 3, 5, 2, 5, 1, 8, 2]"
          gradient="['#00ac84']"
          :barWidth="10"
          :rounding="4"
    />
```

Output:

![image](https://user-images.githubusercontent.com/32278933/101487344-b8836b80-3966-11eb-91dc-e985ffc3105d.png)

**Comment by smknstd** [comment]
I think I fixed this in master but repo missed a new tag. Can you cheeckout with v0.1.7 ?

**Comment by DavidGolodetsky** [comment]
Thank you for the response. I'll wait for 1.7 on npm ;)

**Comment by smknstd** [comment]
I updated package.json but it seems I don't have the rights to publish it to npm with `npm publish` ...

**Comment by DeviaVir** [comment]
0.1.8 has been pushed to npm
